### ISSUE TITLE
VCS balloon trophy not unlocked

### ISSUE THREAD

**Issue by pmsobrado** [Freakler/psp-gta_trophies#7]
@Freakler Could it be because of this line?

https://github.com/Freakler/psp-gta_trophies/blob/3eb3cfebfc8d5de6cc1a031763d91664b17bbd75/source/main.c#L404

Shouldn't it be VCS instead of LCS?

I tested all other VCS trophies, they all work OK :)

I hope you can fix this to make this plugin 100% enjoyable. It should be an easy fix.

**Comment by Freakler** [comment]
It obviously should!!
Pushed and new release created! thank you

**Comment by pmsobrado** [comment]
Thank YOU! I can't try it right now, it will probably work, but I'll confirm it anyway as soon as I can :)

**Comment by pmsobrado** [comment]
Indeed, it worked. Thanks again.
